// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCngTz-4SNHiatPa5nEwd1qvOOPW3w_Jak',
    appId: '1:331902335113:web:310c1213dc46afd59d2e58',
    messagingSenderId: '331902335113',
    projectId: 'flayers-259da',
    authDomain: 'flayers-259da.firebaseapp.com',
    storageBucket: 'flayers-259da.firebasestorage.app',
    measurementId: 'G-KES64NGW7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nk0XHJqdAhI-OD490P81dCkFwJ_qUYw',
    appId: '1:331902335113:android:266ce445007902229d2e58',
    messagingSenderId: '331902335113',
    projectId: 'flayers-259da',
    storageBucket: 'flayers-259da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDG82QoNy2m4VIgt6GioSXTBWn0t9_ECg',
    appId: '1:331902335113:ios:c8c70db222d9e6549d2e58',
    messagingSenderId: '331902335113',
    projectId: 'flayers-259da',
    storageBucket: 'flayers-259da.firebasestorage.app',
    iosBundleId: 'com.example.flayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDG82QoNy2m4VIgt6GioSXTBWn0t9_ECg',
    appId: '1:331902335113:ios:c8c70db222d9e6549d2e58',
    messagingSenderId: '331902335113',
    projectId: 'flayers-259da',
    storageBucket: 'flayers-259da.firebasestorage.app',
    iosBundleId: 'com.example.flayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCngTz-4SNHiatPa5nEwd1qvOOPW3w_Jak',
    appId: '1:331902335113:web:a9d0e2089c0e6e319d2e58',
    messagingSenderId: '331902335113',
    projectId: 'flayers-259da',
    authDomain: 'flayers-259da.firebaseapp.com',
    storageBucket: 'flayers-259da.firebasestorage.app',
    measurementId: 'G-JTSBY48PS4',
  );
}
